name: Publish to GitHub Packages

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        node-version: [20.x, 22.15.1]
        arch: [x64]
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@printags'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build binary
        run: |
          # We're building directly with node-pre-gyp instead of npm ci,
          # to make sure we get a binary even if we can't download one
          npx node-pre-gyp rebuild
          
          # Show the built binary
          dir build\Release
          
          # Create proper directory structure for node-pre-gyp package
          mkdir package\build
          mkdir package\build\Release
          copy build\Release\pcsclite.node package\build\Release\
          
          # Create the tarball
          cd package
          tar -czf ..\win32-x64.tar.gz build
          cd ..
          
          # Debug output
          dir *.tar.gz
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: win32-x64-${{ matrix.node-version }}
          path: win32-x64.tar.gz

  publish:
    needs: [build-windows]
    runs-on: windows-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.15.1
          registry-url: 'https://npm.pkg.github.com'
          scope: '@printags'
      
      # We don't need to run npm ci here as we don't use any dependencies for this job
      # Just downloading the artifacts and publishing
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      - name: Prepare artifacts
        run: |
          dir artifacts
          # Renaming artifacts with node version suffix
          mkdir release
          copy artifacts\win32-x64-20.x\win32-x64.tar.gz release\win32-x64-node20.tar.gz
          copy artifacts\win32-x64-22.15.1\win32-x64.tar.gz release\win32-x64-node22.tar.gz
      
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            release/win32-x64-node20.tar.gz
            release/win32-x64-node22.tar.gz
      
      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}