name: Publish to GitHub Packages

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        node-version: [20.x]
        arch: [x64]
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@printags'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build binary
        run: |
          # Build with node-gyp
          node-gyp rebuild
          
          # Show the built binary
          dir build\Release
          
          # Create proper directory structure for node-pre-gyp
          mkdir package\build
          mkdir package\build\Release
          copy build\Release\pcsclite.node package\build\Release\
          
          # Create the tarball
          cd package
          tar -czf ..\win32-x64.tar.gz build
          cd ..
          
          # Debug output
          dir *.tar.gz
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: win32-x64
          path: win32-x64.tar.gz

  publish:
    needs: [build-windows]
    runs-on: windows-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          registry-url: 'https://npm.pkg.github.com'
          scope: '@printags'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: win32-x64
          path: .
      
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: win32-x64.tar.gz
      
      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}